### Xbox One Chelyaba Egles
GET https://www.easports.com/iframe/nhl14proclubs/api/platforms/xboxone/clubs/348482/seasonalStats
  ?filters=pretty,extrap,invert
Accept: application/json

### PS4 HC Virtuoso
GET https://www.easports.com/iframe/nhl14proclubs/api/platforms/ps4/clubs/295491/seasonalStats
  ?filters=pretty,extrap,invert
Accept: application/json

###